### ISSUE TITLE
Add parameter querying to the backend endpoints

### ISSUE THREAD

**Issue by milachae** [SELab-2/Dr-Trottoir-2#283]
It would be usefull if we could pass parameters to the backend when we send a get request.
For example, a start- and enddate in the schedule endpoint.
`/schedule/?startdate=...`

We would not have to get all the entries in the frontend anymore.
If this is implemented, I can easily change the services to  work with these parameters.

This can be done with filtering in the django rest-framework:
https://www.django-rest-framework.org/api-guide/filtering/

**Comment by wwelvaer** [comment]
Should the data still be returned in pages when using query parameters (like the normal /get does atm)?

**Comment by milachae** [comment]
Ideally yes
