### ISSUE TITLE
/admin/ route is ambiguous

### ISSUE THREAD

**Issue by JasperJanin** [SELab-2/Dr-Trottoir-2#294]
The sel2-2.ugent.be/admin route points to the django admin console, so either the frontend admin pages need a different name or the django admin panel should be moved.

**Comment by eliasnijs** [comment]
I would change frontend to 'beheer'. We need to use Dutch not English also.

**Comment by eliasnijs** [comment]
We could also use 'beheerd' since we are using 'student' for the student pages.

**Comment by eliasnijs** [comment]
I would keep the 'student' since this is their internal terminology. 'beheer' is okay for me.
